export enum AuthActionTypes {
  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',

  GET_CURRENT_USER = 'GET_CURRENT_USER',

  USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE = 'USER_LOGIN_FAILURE',
}

export enum BackgroundActionTypes {
  CREATE_BACKGROUND_REQUEST = 'CREATE_BACKGROUND_REQUEST',
  CREATE_BACKGROUND_SUCCESS = 'CREATE_BACKGROUND_SUCCESS',
  CREATE_BACKGROUND_FAILURE = 'CREATE_BACKGROUND_FAILURE',

  FETCH_BACKGROUNDS_REQUEST = 'FETCH_BACKGROUNDS_REQUEST',
  FETCH_BACKGROUNDS_SUCCESS = 'FETCH_BACKGROUNDS_SUCCESS',
  FETCH_BACKGROUNDS_FAILURE = 'FETCH_BACKGROUNDS_FAILURE',

  SET_ACTIVE_REQUEST = 'SET_ACTIVE_REQUEST',
  SET_ACTIVE_SUCCESS = 'SET_ACTIVE_SUCCESS',
  SET_ACTIVE_FAILURE = 'SET_ACTIVE_FAILURE',

  FETCH_ACTIVE_BG = 'FETCH_ACTIVE_BG',

  DELETE_BACKGROUND_REQUEST = 'DELETE_BACKGROUND_REQUEST',
  DELETE_BACKGROUND_SUCCESS = 'DELETE_BACKGROUND_SUCCESS',
  DELETE_BACKGROUND_FAILURE = 'DELETE_BACKGROUND_FAILURE',
}
export enum BioActionTypes {
  FETCH_BIO_REQUEST = 'FETCH_BIO_REQUEST',
  FETCH_BIO_SUCCESS = 'FETCH_BIO_SUCCESS',
  FETCH_BIO_FAILURE = 'FETCH_BIO_FAILURE',

  UPDATE_BIO_REQUEST = 'UPDATE_BIO_REQUEST',
  UPDATE_BIO_SUCCESS = 'UPDATE_BIO_SUCCESS',
  UPDATE_BIO_FAILURE = 'UPDATE_BIO_FAILURE',
}

export enum CartActionTypes {
  ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
  CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART',

  CLEAR_CART = 'CLEAR_CART',
  TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN',

  UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS',
  UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD',
}

export enum ModalActionTypes {
  TOGGLE_MODAL = 'TOGGLE_MODAL',
}

export enum NavActionTypes {
  TOGGLE_NAV = 'TOGGLE_NAV',
}
export enum LightboxActionTypes {
  SET_DISPLAY_LIGHTBOX = 'SET_DISPLAY_LIGHTBOX',
}

export enum OrdertActionTypes {
  CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE',

  UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST',
  UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS',
  UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE',

  PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST',
  PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS',
  PAY_ORDER_FAILURE = 'PAY_ORDER_FAILURE',
  PAY_ORDER_RESET = 'PAY_ORDER_RESET',
}

export enum AdminOrdertActionTypes {
  ADMIN_GET_ORDER_REQUEST = 'ADMIN_GET_ORDER_REQUEST',
  ADMIN_GET_ORDER_SUCCESS = 'ADMIN_GET_ORDER_SUCCESS',
  ADMIN_GET_ORDER_FAILURE = 'ADMIN_GET_ORDER_FAILURE',

  GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE',
}

export enum PrintActionTypes {
  ADMIN_FETCH_PRINTS_REQUEST = 'ADMIN_FETCH_PRINTS_REQUEST',
  ADMIN_FETCH_PRINTS_SUCCESS = 'ADMIN_FETCH_PRINTS_SUCCESS',
  ADMIN_FETCH_PRINTS_FAILURE = 'ADMIN_FETCH_PRINTS_FAILURE',

  CREATE_PRINT_REQUEST = 'CREATE_PRINT_REQUEST',
  CREATE_PRINT_SUCCESS = 'CREATE_PRINT_SUCCESS',
  CREATE_PRINT_FAILURE = 'CREATE_PRINT_FAILURE',

  FETCH_PRINTS_REQUEST = 'FETCH_PRINTS_REQUEST',
  FETCH_PRINTS_SUCCESS = 'FETCH_PRINTS_SUCCESS',
  FETCH_PRINTS_FAILURE = 'FETCH_PRINTS_FAILURE',

  FETCH_PRINT_REQUEST = 'FETCH_PRINT_REQUEST',
  FETCH_PRINT_SUCCESS = 'FETCH_PRINT_SUCCESS',
  FETCH_PRINT_FAILURE = 'FETCH_PRINT_FAILURE',

  UPDATE_PRINT_REQUEST = 'UPDATE_PRINT_REQUEST',
  UPDATE_PRINT_SUCCESS = 'UPDATE_PRINT_SUCCESS',
  UPDATE_PRINT_FAILURE = 'UPDATE_PRINT_FAILURE',

  DELETE_PRINT_REQUEST = 'DELETE_PRINT_REQUEST',
  DELETE_PRINT_SUCCESS = 'DELETE_PRINT_SUCCESS',
  DELETE_PRINT_FAILURE = 'DELETE_PRINT_FAILURE',
}

export enum ProjectActionTypes {
  ADMIN_FETCH_PROJECT_REQUEST = 'ADMIN_FETCH_PROJECT_REQUEST',
  ADMIN_FETCH_PROJECT_SUCCESS = 'ADMIN_FETCH_PROJECT_SUCCESS',
  ADMIN_FETCH_PROJECT_FAILURE = 'ADMIN_FETCH_PROJECT_FAILURE',

  ADMIN_FETCH_PROJECTS_REQUEST = 'ADMIN_FETCH_PROJECTS_REQUEST',
  ADMIN_FETCH_PROJECTS_SUCCESS = 'ADMIN_FETCH_PROJECTS_SUCCESS',
  ADMIN_FETCH_PROJECTS_FAILURE = 'ADMIN_FETCH_PROJECTS_FAILURE',

  CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE',

  FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE',

  FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST',
  FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS',
  FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE',

  UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE',

  ADD_PROJECT_IMG_REQUEST = 'ADD_PROJECT_IMG_REQUEST',
  ADD_PROJECT_IMG_SUCCESS = 'ADD_PROJECT_IMG_SUCCESS',
  ADD_PROJECT_IMG_FAILURE = 'ADD_PROJECT_IMG_FAILURE',

  DELETE_PROJECT_IMAGE = 'DELETE_PROJECT_IMAGE',
  SWAP_PROJECT_IMAGE = 'SWAP_PROJECT_IMAGE',

  DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST',
  DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE',
}

export enum UploadActionTypes {
  UPLOAD_REQUEST = 'UPLOAD_REQUEST',
  UPLOAD_SUCCESS = 'UPLOAD_SUCCESS',
  UPLOAD_FAILURE = 'UPLOAD_FAILURE',
}
